#!/bin/sh

BUILDDIR=/go/src/gitlab.com/$CI_PROJECT_PATH
DEST=`pwd`/binaries
GOARCH=amd64

mkdir -p ${DEST}/
mkdir -p `dirname $BUILDDIR`
ln -s `pwd` $BUILDDIR
cd $BUILDDIR

for GOOS in windows linux darwin; do
  BINARY="${DEST}/${CI_PROJECT_NAME}_${CI_COMMIT_TAG}"
  ARCHIVE="${BINARY}-${GOOS}-${GOARCH}.zip"
  SUM="${BINARY}-${GOOS}-${GOARCH}.sha256"
  CGO_ENABLED=0 go build -o $BINARY
  strip $BINARY
  sha256sum $BINARY | sed -e 's|\(\w\+\s\+\).*/\(.*\)$|\1\2|' > $SUM
  zip -j $ARCHIVE $BINARY
  rm -f $BINARY
done
